# Generated by Django 6.0.6 on 2026-06-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='地点名称')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址描述')),
                ('building', models.CharField(blank=True, max_length=50, null=True, verbose_name='所属建筑')),
                ('category', models.CharField(choices=[('teaching', '教学楼'), ('dormitory', '宿舍'), ('canteen', '食堂'), ('office', '办公楼'), ('other', '其他')], default='other', max_length=20, verbose_name='分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '校内地点',
                'verbose_name_plural': '校内地点',
                'ordering': ['category', 'name'],
            },
        ),
    ]
