# Generated by Django 6.0.6 on 2026-06-09 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_nav', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campuslocation',
            options={'ordering': ['name'], 'verbose_name': '校内地点', 'verbose_name_plural': '校内地点'},
        ),
        migrations.RemoveField(
            model_name='campuslocation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='campuslocation',
            name='building',
        ),
        migrations.RemoveField(
            model_name='campuslocation',
            name='category',
        ),
    ]
