# Generated by Django 6.0.3 on 2026-05-28 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='车牌号')),
                ('owner_name', models.CharField(max_length=100, verbose_name='所属人')),
                ('owner_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='首次登记时间')),
            ],
            options={
                'verbose_name': '外来车辆档案',
                'verbose_name_plural': '外来车辆档案',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='车牌号')),
                ('vehicle_type', models.CharField(choices=[('school_bus', '校车'), ('staff', '教职工车辆'), ('official', '公务车辆'), ('visitor', '访客车辆'), ('delivery', '送货车辆')], default='staff', max_length=20, verbose_name='车辆类型')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='品牌')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='颜色')),
                ('owner_name', models.CharField(max_length=100, verbose_name='所属人/部门')),
                ('owner_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='是否黑名单')),
                ('blacklist_reason', models.TextField(blank=True, null=True, verbose_name='拉黑原因')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '在校车辆档案',
                'verbose_name_plural': '在校车辆档案',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=50, verbose_name='访客姓名')),
                ('visitor_phone', models.CharField(max_length=20, verbose_name='访客电话')),
                ('plate_number', models.CharField(max_length=20, verbose_name='车牌号')),
                ('host_name', models.CharField(max_length=50, verbose_name='被访人')),
                ('host_department', models.CharField(blank=True, max_length=100, null=True, verbose_name='被访部门')),
                ('expected_time', models.DateTimeField(verbose_name='预计进校时间')),
                ('purpose', models.TextField(verbose_name='事由')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝'), ('arrived', '已到访'), ('left', '已离开')], default='pending', max_length=20, verbose_name='状态')),
                ('approver', models.CharField(blank=True, max_length=50, null=True, verbose_name='审批人')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '访客预约',
                'verbose_name_plural': '访客预约',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntryExitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, verbose_name='车牌号')),
                ('record_type', models.CharField(choices=[('entry', '进校'), ('exit', '出校')], max_length=10, verbose_name='进出类型')),
                ('record_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='进出时间')),
                ('driver_name', models.CharField(max_length=50, verbose_name='驾驶员姓名')),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='驾驶员电话')),
                ('passenger_count', models.PositiveIntegerField(default=1, verbose_name='同行人数')),
                ('goods_info', models.TextField(blank=True, null=True, verbose_name='货物信息')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='事由')),
                ('expected_leave_time', models.DateTimeField(blank=True, null=True, verbose_name='预计离校时间')),
                ('approver', models.CharField(blank=True, max_length=50, null=True, verbose_name='审批人')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('external_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='vehicle_mgmt.externalvehicle', verbose_name='外来车辆')),
                ('school_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='vehicle_mgmt.schoolvehicle', verbose_name='在校车辆')),
            ],
            options={
                'verbose_name': '进出记录',
                'verbose_name_plural': '进出记录',
                'ordering': ['-record_time'],
                'indexes': [models.Index(fields=['-record_time'], name='vehicle_mgm_record__91ac54_idx'), models.Index(fields=['record_type'], name='vehicle_mgm_record__3ab184_idx')],
            },
        ),
    ]
