# Generated by Django 6.0.3 on 2026-05-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonMotorVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(help_text='范围 001~999，必须3位数字', max_length=3, unique=True, verbose_name='编号牌')),
                ('vehicle_type', models.CharField(choices=[('bicycle', '自行车'), ('ebike', '电动车'), ('tricycle', '三轮车'), ('other', '其他')], default='ebike', max_length=20, verbose_name='车辆类型')),
                ('owner_name', models.CharField(max_length=100, verbose_name='所属人')),
                ('owner_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='品牌')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='颜色')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '非机动车档案',
                'verbose_name_plural': '非机动车档案',
                'ordering': ['number_plate'],
            },
        ),
    ]
