# Generated by Django 6.0.6 on 2026-06-09 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_mgmt', '0002_nonmotorvehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolvehicle',
            options={'ordering': ['-created_at'], 'verbose_name': '校内车辆档案', 'verbose_name_plural': '校内车辆档案'},
        ),
        migrations.AddField(
            model_name='visitorappointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.CreateModel(
            name='QRPassToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='令牌')),
                ('expires_at', models.DateTimeField(verbose_name='有效期至')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='核销时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_token', to='vehicle_mgmt.visitorappointment', verbose_name='关联预约')),
            ],
            options={
                'verbose_name': 'QR 通行令牌',
                'verbose_name_plural': 'QR 通行令牌',
            },
        ),
    ]
